[WIP]: Add crashes since method
badoo/ios-device-server pull request #29
Opened 2018-12-19 15:12 UTC by NickAb

2018-12-20 10:20 UTC, fr0l requested changes

2018-12-20 10:20 UTC, fr0l commented on device-server/src/main/kotlin/com/badoo/automation/deviceserver/DeviceServer.kt
> +import java.time.Duration
looks like redundant import

2018-12-20 10:20 UTC, fr0l commented on device-server/src/main/kotlin/com/badoo/automation/deviceserver/host/ISimulatorsNode.kt
> +import com.badoo.automation.deviceserver.ios.device.Device
redundant import ?

2018-12-20 10:20 UTC, fr0l commented on device-server/src/main/kotlin/com/badoo/automation/deviceserver/host/management/IDeviceManager.kt
> +import com.badoo.automation.deviceserver.ios.device.Device
redundant import?

2018-12-20 10:20 UTC, fr0l commented on device-server/src/main/kotlin/com/badoo/automation/deviceserver/ios/simulator/Simulator.kt
> +                null
maybe log reason if not successful ?

2018-12-21 15:37 UTC, NickAb commented
@fr0l, review please

2018-12-31 11:11 UTC, merged