Add method to reset Media folder
badoo/ios-device-server pull request #52
Opened 2019-04-30 13:20 UTC by NickAb

2019-04-30 15:39 UTC, fr0l commented on device-server/src/main/kotlin/com/badoo/automation/deviceserver/ios/simulator/data/Media.kt
> +        val shellCmd = "rm $imagesPath/**/* $photoDataPath*; touch $photoDataPath"
what if there isn't any ? how about make it 
```
rm -f
```

2019-04-30 15:40 UTC, fr0l approved these changes

2019-04-30 16:07 UTC, fr0l requested changes

2019-04-30 16:07 UTC, fr0l commented on device-server/src/main/kotlin/com/badoo/automation/deviceserver/ios/simulator/data/Media.kt
> +            throw RuntimeException("Could not restart assetsd service")
let's print stderr here as well

2019-04-30 16:09 UTC, fr0l commented on device-server/src/main/kotlin/com/badoo/automation/deviceserver/ios/simulator/data/Media.kt
> +        val removeCmd = "rm $imagesPath/**/* $photoDataPath*; touch $photoDataPath"
how about using rm -f
here

2019-05-01 10:13 UTC, fr0l approved these changes

2019-05-01 10:13 UTC, merged

2019-05-01 10:40 UTC, NickAb commented
If we will need to list available media from the gallery or delete specific photos from gallery instead of wiping it out completely, we can take a look at https://github.com/geiszla/iOSLib for reference.