Add method to list media for iOS Simulator
badoo/ios-device-server pull request #65
Opened 2019-09-25 11:54 UTC by sergey-plevako-badoo

Added a method to list the files in data/Media/DCIM/100APPLE which shows the number of media added by `xcrun simctl addmedia` command

2019-12-20 11:14 UTC, fr0l requested changes

2019-12-20 11:14 UTC, fr0l commented on device-server/src/main/kotlin/com/badoo/automation/deviceserver/ios/simulator/data/Media.kt
> +        val listCmd = listOf("ls", "$mediaPath/DCIM/100APPLE")
Let's use single column formatted output of 'ls'

please add argument "-1"

2019-12-20 11:14 UTC, fr0l commented on device-server/src/main/kotlin/com/badoo/automation/deviceserver/data/MediaDto.kt
> +    val url: String)
property name is 'url' , in fact it is a string with file names, that are delimited by 'newline' symbol.

1. let's rename the property to something more relevant.
2. let's return a list of file names - i.e. actually a list of strings, so clients do not have to guess anything.

2019-12-21 17:32 UTC, NickAb commented
You might want to take a look at https://github.com/NickAb/ios-utils.

- It is a CLI tool that runs on a simulator and lets you list and delete media and pasteboards.
- It uses mostly public iOS API, i.e. should be much more stable and less fiddly than working with an underlying simulator file system.
- The only private API used is entitlements keys which are unlikely to change and are the same as ones used by system apps on iOS.

2019-12-23 16:53 UTC, sergey-plevako-badoo commented
Updated in aa2762d

2020-01-24 22:39 UTC, merged